#!/usr/bin/env python3
"""Generate native routines only for Raaka-Tu's seven hot turn scripts."""

import argparse
import pathlib
import sys

from generate_zcompact import CompactBuilder
from generate_zdata import parse_c_arrays
from generate_zscripts import Compiler


ROOT = pathlib.Path(__file__).resolve().parent
SOURCE = ROOT / "gamedata.c"
OUTPUT = ROOT / "zmachine" / "turns.inf"


class TurnCompiler(Compiler):
    def __init__(self, arrays):
        super().__init__(arrays)
        compact = CompactBuilder(arrays)
        compact.build()
        self.text_ids = {
            source: index for index, source
            in enumerate(compact.text_sources, 1)
        }

    def expression(self, node):
        if node.kind == "common":
            return f"AotRunCommon(${node.args[0]:02X})"
        if node.kind == "op" and node.args[0] in (4, 31):
            op, source = node.args
            return f"AotOp{op:02d}Id({self.text_ids[source]})"
        return super().expression(node)

    def render_turns(self):
        _, _, _, objects = self.parse_entries()
        turns = objects[8]
        for node in turns.values():
            self.ensure_function(node)
        lines = [
            "! Auto-generated by generate_zturns.py.",
            "! Only always-polled turn scripts are translated to native Z-code.",
            "",
        ]
        for name, node in self.functions:
            lines.extend(self.render_function(name, node))
            lines.append("")
        lines.extend(self.render_dispatch("AotRunTurnCommand", turns))
        lines.append("")
        return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        arrays = dict(parse_c_arrays(SOURCE.read_text()))
        generated = TurnCompiler(arrays).render_turns()
    except (OSError, ValueError, IndexError) as exc:
        print(f"generate_zturns.py: {exc}", file=sys.stderr)
        return 1
    if args.check:
        try:
            current = OUTPUT.read_text()
        except OSError as exc:
            print(f"generate_zturns.py: {exc}", file=sys.stderr)
            return 1
        if current != generated:
            print(f"{OUTPUT} is stale; run generate_zturns.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is current")
        return 0
    OUTPUT.write_text(generated)
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
