/*
 * Raaka-Tu -- C port for OS-9 Level 2
 * Ported from the annotated 6809 disassembly (raaka-tu.asm)
 *
 * All game data lives in gamedata.c (generated by extract_data.py).
 * This file implements the parser, VM, and game loop.
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

typedef unsigned char  byte;
typedef unsigned short word;

/* ---- game data arrays (from gamedata.c) --------------------------------- */
extern byte chartab[];       /* 40-byte base-40 char translation table       */
extern byte rand_seed[];     /* [0]=multivb, [1..8]=LFSR seed                */
extern byte msg_qverb[];     /* "?VERB?"   plain-ASCII length-prefixed string */
extern byte msg_qwhat[];     /* "?WHAT?"                                     */
extern byte msg_qwhich[];    /* "?WHICH?"                                    */
extern byte msg_qphrase[];   /* "?PHRASE?"                                   */
extern byte phrase_list[];   /* phrase syntax table (raw 5-byte entries)     */
extern byte room_data[];     /* room descriptions & scripts                  */
extern byte obj_data[];      /* object data                                  */
extern byte cmd_data[];      /* general command scripts                      */
extern byte ccmd_data[];     /* common command scripts                       */
extern byte vocab_data[];    /* vocabulary (verbs, nouns, adjs, preps)       */
extern byte prep_data[];     /* preposition list for phrase matching          */

/* ---- list navigation ---------------------------------------------------- */
/*
 * Each "list" is: [tag][len1 {len2}][content...]
 * If len1 bit7 clear: 1-byte length.  If set: 2-byte length ((len1&$7F)<<8 | len2).
 * len gives the number of bytes that FOLLOW the length field(s).
 *
 * list_end_from_len(p)  -- p points at the length byte; returns end pointer,
 *                          sets *content to the first content byte.
 * list_open(p)          -- p points at the tag byte; skips tag+len, returns end.
 * list_skip(p)          -- p points at the length byte (no tag); returns end.
 */

static byte *list_end_from_len(byte *p, byte **content)
{
    word len;
    if (*p & 0x80) {
        len = (word)((*p & 0x7F) << 8) | *(p+1);
        *content = p + 2;
    } else {
        len = *p;
        *content = p + 1;
    }
    return *content + len;
}

/* p points to the tag byte; skip tag+len, set *content_out, return end */
static byte *list_open(byte *p, byte **content_out)
{
    byte *q = p + 1;          /* skip tag */
    return list_end_from_len(q, content_out);
}

/* p points to the length byte (no tag); set *content_out, return end */
static byte *list_skip(byte *p, byte **content_out)
{
    return list_end_from_len(p, content_out);
}

/* Search through a sequence of items (p..list_end) for one whose tag==tag.
 * Each item is [tag][len...][content].
 * Returns pointer to the LENGTH PREFIX byte of the matching item (so callers
 * can pass it directly to print_packed or list_end_from_len).
 * Sets *end_out to the end of the matching item's content.
 * Returns NULL if not found. */
static byte *list_find_tag(byte *p, byte *list_end, byte tag, byte **end_out)
{
    while (p < list_end) {
        byte *content, *sub_end;
        byte sub_tag = *p;
        sub_end = list_open(p, &content);
        if (sub_tag == tag) {
            if (end_out) *end_out = sub_end;
            return p + 1;   /* pointer to the length prefix byte */
        }
        p = sub_end;
    }
    return NULL;
}

/* ---- game state --------------------------------------------------------- */

static byte  g_cur_room;          /* current room number                      */
static byte *g_cur_room_data;     /* pointer to room item content             */
static byte *g_cur_room_end;      /* end of room item content                 */

static byte  g_player_room;       /* player object number = 0x1D              */

static byte  g_var_obj_num;
static byte *g_var_obj_data;
static byte *g_var_obj_end;

static byte  g_noun1_num;
static byte *g_noun1_data;
static byte *g_noun1_end;
static byte  g_noun1_param;       /* loc byte of first noun                   */
static byte  g_noun1_typed;       /* vocab word# if a noun was typed for slot1 */

static byte  g_noun2_num;
static byte *g_noun2_data;
static byte *g_noun2_end;
static byte  g_noun2_param;
static byte  g_noun2_typed;       /* vocab word# if a noun was typed for slot2 */

static byte  g_phrase_form;       /* phrase form number                       */
static byte  g_active_obj;        /* active object (player object number)     */
static byte *g_active_obj_data;
static byte *g_active_obj_end;

static byte  g_verb;
static byte  g_prep;
static byte  g_prep_given;
static byte  g_adj;
static byte  g_cmd_targ;
static byte  g_adj2;
static byte  g_which_need;
static byte  g_which_want;
static byte  g_which_match;
static byte  g_dis_obj_num;
static byte  g_dis_loc;

/* ---- text output -------------------------------------------------------- */
#define LINE_WIDTH  32
#define WORD_MAX    64

static int   g_col;
static char  g_line[LINE_WIDTH+2];
static int   g_line_len;
static char  g_word[WORD_MAX];
static int   g_word_len;

/* Flush accumulated word to the output line, wrapping if needed */
static void flush_word(void)
{
    int needs_space, fits;
    if (g_word_len == 0) return;
    needs_space = (g_line_len > 0) ? 1 : 0;
    fits = (g_line_len + needs_space + g_word_len <= LINE_WIDTH);
    if (!fits && g_line_len > 0) {
        /* Word doesn't fit: flush current line, start fresh */
        g_line[g_line_len] = '\0';
        puts(g_line);
        g_line_len = 0;
        g_col = 0;
        needs_space = 0;
    }
    if (needs_space) {
        g_line[g_line_len++] = ' ';
        g_col++;
    }
    memcpy(g_line + g_line_len, g_word, g_word_len);
    g_line_len += g_word_len;
    g_col = g_line_len;
    g_word_len = 0;
}

static void flush_line(void)
{
    flush_word();
    if (g_line_len > 0) {
        g_line[g_line_len] = '\0';
        puts(g_line);
        g_line_len = 0;
        g_col = 0;
    }
    putchar('\n');
}

static void print_char(int c)
{
    if (c == '\r' || c == '\n') {
        flush_word();
        if (g_line_len > 0) {
            g_line[g_line_len] = '\0';
            puts(g_line);
            g_line_len = 0;
            g_col = 0;
        } else {
            putchar('\n');
        }
        g_word_len = 0;
        return;
    }

    if ((byte)c == 0xCF)   /* VDG cursor marker */
        return;

    if (c == ' ' || c == '\t') {
        flush_word();
        return;
    }

    /* Accumulate non-space char into word buffer */
    if (g_word_len < WORD_MAX - 1)
        g_word[g_word_len++] = (char)c;
}

/* Print len bytes of raw ASCII starting at p, then a space */
static void print_raw(byte *p, int len)
{
    while (len-- > 0)
        print_char(*p++);
    print_char(' ');
}

/* Decode and print packed text.
 * p points to the LENGTH PREFIX byte of a length-prefixed packed block. */
static void print_packed(byte *p)
{
    byte *content;
    byte *end = list_end_from_len(p, &content);
    word remaining = (word)(end - content);

    while (remaining >= 2) {
        word v = ((word)content[1] << 8) | content[0];  /* little-endian */
        int i;
        char decoded[3];
        decoded[2] = chartab[v % 40];
        decoded[1] = chartab[(v / 40) % 40];
        decoded[0] = chartab[v / 1600];
        for (i = 0; i < 3; i++)
            print_char((byte)decoded[i]);
        content  += 2;
        remaining -= 2;
    }
    if (remaining == 1)
        print_char(*content);

    print_char(' ');
}

/* Print a plain [len][chars...] ASCII string followed by CR */
static void print_plain(byte *p)
{
    int len = *p++;
    while (len-- > 0)
        print_char(*p++);
    print_char('\r');
}

/* ---- random number generator -------------------------------------------- */
/* Assembly generates a new random byte at only two sites: once per keystroke
 * while reading input (GetKey, $0B2B), and once per object right before its
 * turn-script runs ($0F95). is_less_equal_last_random ($0FCF) never rolls --
 * it just re-reads the cached byte at $1338, so a single roll is bucketed
 * across every threshold test in a switch. g_last_random mirrors that cache. */
static byte g_rand[8];
static byte g_last_random;

static void rand_init(void)
{
    memcpy(g_rand, rand_seed + 1, 8);   /* skip the multi-verb $00 at [0] */
    g_last_random = g_rand[0];
}

static byte rand_next(void)
{
    int i;
    byte a = g_rand[0];

    for (i = 0; i < 0x17; i++) {
        byte carry;
        int  tap = a & 0x06;
        byte hi, lo;
        int idx;

        carry = (tap == 0 || tap == 6) ? 1 : 0;

        idx = (i + 1) % 8;
        hi  = g_rand[idx];
        hi  = carry ? (byte)((hi >> 1) | 0x80) : (byte)(hi >> 1);
        g_rand[idx] = hi;

        idx = i % 8;
        lo  = g_rand[idx];
        lo  = (hi & 0x01) ? (byte)((lo >> 1) | 0x80) : (byte)(lo >> 1);
        lo &= 0xFE;
        g_rand[idx] = lo;

        a = g_rand[(i+1) % 8];
    }
    g_last_random = g_rand[0];
    return g_rand[0];
}

/* ---- find object by number ---------------------------------------------- */
/* obj_data outer container: [tag=0x00][len2...][content: items...]
 * Each item: [tag][len...][content: loc, score, bits, sublists...]
 * num is a 1-based sequential index (assembly $1133: DECB/BEQ countdown). */

/* Forward declaration — defined after obj_in_cur_room_or_pack */
static int obj_in_cur_room_or_pack(byte num);

/* Return sequential index (1-based) of the FIRST ACCESSIBLE object whose
 * tag byte equals tag (accessible = in current room or carried by player).
 * Falls back to the first matching object if none are accessible,
 * matching assembly $0822's room-aware noun→object resolution. */
static byte obj_seq_from_tag(byte tag)
{
    byte *p = obj_data;
    byte *base_end, *base_content;
    byte count = 0;


    base_end = list_open(p, &base_content);
    p = base_content;
    while (p < base_end) {
        byte obj_tag = *p;
        byte *content, *item_end;
        item_end = list_open(p, &content);
        count++;
        if (obj_tag == tag && obj_in_cur_room_or_pack(count))
            return count;
        p = item_end;
    }
    return 0;  /* no accessible object with this tag */
}

static byte *obj_find_by_num(byte num, byte **out_end)
{
    byte *p = obj_data;
    byte *base_end, *base_content;
    byte count;

    base_end = list_open(p, &base_content);   /* skip outer container tag+len */
    p = base_content;

    count = num;
    while (p < base_end) {
        byte *content, *item_end;
        item_end = list_open(p, &content);
        if (--count == 0) {
            if (out_end) *out_end = item_end;
            return content;
        }
        p = item_end;
    }
    return NULL;
}

/* ---- vocabulary matching ------------------------------------------------ */
#define MAX_TOKENS 32
static byte  g_token_buf[MAX_TOKENS * 3];
static int   g_token_count;

#define INPUT_LEN 33
static char  g_input[INPUT_LEN];

/* Try to match the word at g_input[pos] against vocab list p.
 * Returns word number (non-zero) on match; 0 otherwise.
 * Sets *end_pos to position just past the matched word. */
static int vocab_match_list(byte *p, int pos, int *end_pos)
{
    while (*p != 0) {
        int vlen = *p++;
        int i, match = 1;
        for (i = 0; i < vlen; i++) {
            char sc = g_input[pos + i];
            if (sc == '\0' || (byte)sc != p[i]) {
                match = 0;
                break;
            }
        }
        if (match) {
            char bc = g_input[pos + vlen];
            if (bc == '\0' || !isalpha((byte)bc) || vlen >= 6) {
                int wnum = p[vlen];
                if (end_pos) {
                    int ep = pos + vlen;
                    while (g_input[ep] && isalpha((byte)g_input[ep])) ep++;
                    *end_pos = ep;
                }
                return wnum;
            }
        }
        p += vlen + 1;
    }
    return 0;
}

/* Parse input line into tokens (g_token_buf / g_token_count).
 * vocab_data layout: [empty-ignore $00][verbs...][nouns...][adjs...][preps...] */
static void parse_input(void)
{
    byte *list_ptrs[5];
    int  li, pos;

    {
        byte *p = vocab_data;
        /* vocab_data has 4 sublists: 0=ignore, 1=verbs, 2=nouns, 3=adjs.
         * Prepositions are in the separate prep_data array (list index 4). */
        for (li = 0; li < 4; li++) {
            list_ptrs[li] = p;
            while (*p != 0) {
                int wlen = *p++;
                p += wlen + 1;
            }
            p++;   /* skip $00 terminator */
        }
        list_ptrs[4] = prep_data;
    }

    g_token_count = 0;
    pos = 0;

    while (g_input[pos] != '\0') {
        int end_pos = pos;
        int found_type = 0, found_num = 0;

        while (g_input[pos] == ' ') pos++;
        if (g_input[pos] == '\0') break;

        if (vocab_match_list(list_ptrs[0], pos, &end_pos)) {
            pos = end_pos;
            continue;
        }

        for (li = 1; li <= 4; li++) {
            int wnum = vocab_match_list(list_ptrs[li], pos, &end_pos);
            if (wnum) {
                found_type = li;
                found_num  = wnum;
                break;
            }
        }

        if (!found_type) {
            while (g_input[pos] && isalpha((byte)g_input[pos])) pos++;
            continue;
        }

        if (g_token_count < MAX_TOKENS) {
            int tok_pos = g_token_count * 3;
            g_token_buf[tok_pos + 0] = (byte)found_type;
            g_token_buf[tok_pos + 1] = (byte)found_num;
            g_token_buf[tok_pos + 2] = (byte)pos;
            g_token_count++;
        }
        pos = end_pos;
    }
}

/* Walk token buffer and fill g_verb, g_prep, g_noun1*, g_noun2*, etc. */
static void decode_tokens(void)
{
    int i, noun_count = 0;

    g_verb = 0; g_prep = 0; g_prep_given = 0;
    g_adj  = 0; g_adj2 = 0; g_cmd_targ = 0;
    g_noun1_num = 0; g_noun2_num = 0;
    g_noun1_data = NULL; g_noun1_end = NULL;
    g_noun2_data = NULL; g_noun2_end = NULL;

    for (i = 0; i < g_token_count; i++) {
        byte list_type = g_token_buf[i*3 + 0];
        byte word_num  = g_token_buf[i*3 + 1];
        switch (list_type) {
        case 1:
            /* Assembly $06DF: last verb in input wins (overwrites prior verb).
             * "GO WEST" → verb=WEST, not GO. cmd_targ tracks the first verb. */
            g_verb = word_num;
            if (!g_cmd_targ) g_cmd_targ = word_num;
            break;
        case 2: {
            /* word_num is the vocab word number = object tag byte.
             * Convert to sequential object index (assembly $0822 behavior).
             * Nouns after a preposition belong in noun2 slot; nouns before
             * (or with no prep) fill noun1 first, then noun2. */
            byte seq = obj_seq_from_tag(word_num);
            if (g_prep_given) {
                if (!g_noun2_num) { g_noun2_num = seq; g_noun2_typed = word_num; }
            } else {
                if (!g_noun1_num) { g_noun1_num = seq; g_noun1_typed = word_num; noun_count++; }
                else if (!g_noun2_num) { g_noun2_num = seq; g_noun2_typed = word_num; noun_count++; }
            }
            break;
        }
        case 3:
            if (!g_adj) g_adj = word_num; else g_adj2 = word_num;
            break;
        case 4:
            if (!g_prep) { g_prep = word_num; g_prep_given = 1; }
            break;
        }
    }
}

/* ---- find phrase form --------------------------------------------------- */
/* Assembly $08D2: scan room/pack for objects where (bits & mask) == mask.
 * Returns 1-based sequential index of the single match, 0 if none, 255 if >1. */
static byte scan_obj_by_mask(byte mask)
{
    byte *p = obj_data;
    byte *base_end, *base_content;
    byte count = 0, found = 0;

    base_end = list_open(p, &base_content);
    p = base_content;
    while (p < base_end) {
        byte *content, *item_end;
        item_end = list_open(p, &content);
        count++;
        if (obj_in_cur_room_or_pack(count)) {
            if ((content[2] & mask) == mask) {
                if (found) return 255;
                found = count;
            }
        }
        p = item_end;
    }
    return found;
}

/* phrase_list: 5-byte entries [verb][prep][noun1_mask][noun2_mask][form]
 * Returns phrase form (>0) on success, 0 if no verb match found,
 * -1 if a verb+prep match was found but noun scan failed (?WHAT?),
 * or -2 if a verb+prep match was found but the user gave a noun the
 * phrase doesn't take (?PHRASE?, assembly $07B7/$07DD). */
static int find_phrase_form(void)
{
    byte *p = phrase_list;
    while (*p != 0) {
        byte pv   = p[0];
        byte pp   = p[1];
        byte pn1  = p[2];
        byte pn2  = p[3];
        byte form = p[4];

        if (pv != g_verb)                             { p += 5; continue; }
        /* Assembly $0791-$0798: skip if user gave a prep the phrase doesn't have.
         * (NOT: skip if phrase has a prep the user didn't match.) */
        if (g_prep != 0 && g_prep != pp)              { p += 5; continue; }

        /* Assembly $079C-$07B3: noun1 check.
         * If phrase needs n1 but user gave none, scan room by mask ($08D2).
         * Zero or multiple matches → immediate ?WHAT? error (assembly $095A).
         * If user gave n1, proceed directly (no mask validation). */
        if (pn1 != 0 && g_noun1_num == 0) {
            byte found = scan_obj_by_mask(pn1);
            if (found == 0 || found == 255) return -1;
            g_noun1_num = found;
        }
        /* Assembly $07B4-$07B7: phrase doesn't take a first noun, but user gave
         * one anyway → ?PHRASE? */
        else if (pn1 == 0 && g_noun1_num != 0) {
            return -2;
        }

        /* Assembly $07BD-$07D8: noun2 check — same logic. */
        if (pn2 != 0 && g_noun2_num == 0) {
            byte found = scan_obj_by_mask(pn2);
            if (found == 0 || found == 255) return -1;
            g_noun2_num = found;
        }
        /* Assembly $07DA-$07DD: phrase doesn't take a second noun, but user
         * gave one anyway → ?PHRASE? */
        else if (pn2 == 0 && g_noun2_num != 0) {
            return -2;
        }

        return form;
    }
    return 0;
}

/* ---- forward declarations ----------------------------------------------- */
static int exec_script(byte *p, byte *end);
static int exec_one(byte **pp, byte *end);

/* ---- find room data ----------------------------------------------------- */
/* room_data outer container: [tag=0x00][len2...][content: room items...]
 * Each room item: [tag=room_num][len...][content: flag_byte, sublists...]
 * Room sublist tags: 0x03=description, 0x07=noun1 script, etc.
 * Returns pointer to room item content; sets *out_end if not NULL. */
static byte *room_find(byte num, byte **out_end)
{
    byte *p = room_data;
    byte *base_end, *base_content;

    base_end = list_open(p, &base_content);   /* skip outer container tag+len */
    p = base_content;

    while (p < base_end) {
        byte tag = *p;
        byte *content, *item_end;
        item_end = list_open(p, &content);
        if (tag == num) {
            if (out_end) *out_end = item_end;
            return content;
        }
        p = item_end;
    }
    return NULL;
}

/* ---- go to a room ------------------------------------------------------- */
static void go_room(byte room_num)
{
    byte *re;
    g_cur_room      = room_num;
    g_cur_room_data = room_find(room_num, &re);
    g_cur_room_end  = re;
}

/* ---- print room description --------------------------------------------- */
/* Room content: [flags_byte=0x00][sublists starting with tag=0x03 desc...]
 * Assembly 0D4A-0D92: print room description, then print descriptions of all
 * objects whose loc == CUR_ROOM (using each object's tag=0x03 sublist). */
static void print_room_desc(void)
{
    byte *p, *base_end, *base_content;

    if (g_cur_room_data) {
        byte *rd = g_cur_room_data + 1;   /* skip flags byte */
        byte *len_ptr = list_find_tag(rd, g_cur_room_end, 0x03, NULL);
        if (len_ptr)
            print_packed(len_ptr);
        print_char('\r');
    }

    /* print descriptions of objects in the current room (assembly 0D65-0D92) */
    base_end = list_open(obj_data, &base_content);
    p = base_content;
    while (p < base_end) {
        byte *content, *item_end;
        item_end = list_open(p, &content);
        if (content[0] == g_cur_room) {
            byte *desc = list_find_tag(content + 3, item_end, 0x03, NULL);
            if (desc)
                print_packed(desc);
        }
        p = item_end;
    }
}

/* ---- print object short name (sublist tag 0x02) ------------------------- */
static void print_obj_name(byte *obj_content, byte *obj_end)
{
    byte *len_ptr;
    if (!obj_content || !obj_end) return;
    /* object content: [loc][score][bits][sublists...]; skip first 3 bytes */
    len_ptr = list_find_tag(obj_content + 3, obj_end, 0x02, NULL);
    if (len_ptr)
        print_packed(len_ptr);
}

/* ---- check if object is in current room or carried by active object -----
 * Mirrors assembly $08AA: in cur_room → yes; loc=0 → no; loc=0xFF → yes;
 * loc has high bit → in a real room (not carried) → no;
 * loc==active_obj → yes; else follow the ownership chain. */
static int obj_in_cur_room_or_pack(byte num)
{
    byte *content = obj_find_by_num(num, NULL);
    byte loc;
    if (!content) return 0;
    loc = content[0];
    while (1) {
        if (loc == g_cur_room)   return 1;
        if (loc == 0)            return 0;
        if (loc == 0xFF)         return 1;
        if (loc & 0x80)          return 0;
        if (loc == g_active_obj) return 1;
        content = obj_find_by_num(loc, NULL);
        if (!content) return 0;
        loc = content[0];
    }
}

/* Follow ownership chain to check if object is carried by active object */
static int obj_owned_by_active(byte *content)
{
    byte loc;
    if (!content) return 0;
    loc = content[0];
    while (1) {
        if (loc == 0)            return 0;
        if (loc == g_active_obj) return 1;
        if (loc & 0x80)          return 0;
        content = obj_find_by_num(loc, NULL);
        if (!content) return 0;
        loc = content[0];
    }
}

/* ---- VM opcode implementations ------------------------------------------ */
/* Each opcode handler:
 *   pp  = pointer to instruction pointer (already past the opcode byte)
 *   end = end of the current script scope
 * Returns 0=continue, 1=stop/success, 2=restart */

/* 0x00: GoRoom+Print -- go to room [*pp], print description.
 * Assembly 0D4A: PrintRoomDescription returns immediately if active_obj != 0x1D (player). */
static int op_go_room_print(byte **pp, byte *end)
{
    byte room = *(*pp)++;
    go_room(room);
    {
        byte *ac = obj_find_by_num(g_active_obj, NULL);
        if (ac) ac[0] = room;
    }
    if (g_active_obj == g_player_room)
        print_room_desc();
    return 1;
}

/* 0x01: is_in_pack_or_current_room -- object accessible from current context */
static int op_check_obj(byte **pp, byte *end)
{
    byte num = *(*pp)++;
    return obj_in_cur_room_or_pack(num);
}

/* 0x02: is_owned_by_ACTIVE -- check if object is carried by the active obj */
static int op_is_owned_by_active(byte **pp, byte *end)
{
    byte num = *(*pp)++;
    byte *content = obj_find_by_num(num, NULL);
    return obj_owned_by_active(content);
}

/* 0x03: CmpObjRoom -- read [val][obj_num], compare obj's room with val */
static int op_cmp_obj_room(byte **pp, byte *end)
{
    byte target_room = *(*pp)++;
    byte obj_num     = *(*pp)++;
    byte *content = obj_find_by_num(obj_num, NULL);
    if (!content) return 0;
    return (content[0] == target_room) ? 1 : 0;
}

/* 0x04: PrintMsg -- print inline length-prefixed packed message
 * Assembly L0DC3: only prints when active_obj == 0x1D (player);
 * always advances pointer and returns success (clra; rts = Z=1). */
static int op_print_msg(byte **pp, byte *end)
{
    byte *msg = *pp;
    byte *content;
    byte *msg_end = list_end_from_len(msg, &content);
    if (g_active_obj == g_player_room)
        print_packed(msg);
    *pp = msg_end;
    return 1;
}

/* 0x05: is_less_equal_last_random -- compare the CACHED random byte against
 * [*pp]. Assembly ($0FCF) never rolls here; it re-reads $1338, which is only
 * refreshed at the two sites noted above rand_next(). */
static int op_cmp_rand(byte **pp, byte *end)
{
    byte threshold = *(*pp)++;
    return (g_last_random <= threshold) ? 1 : 0;
}

/* 0x06: PrintInvent -- print all objects carried by player */
static int op_print_invent(byte **pp, byte *end)
{
    byte *p = obj_data;
    byte *base_end, *base_content;

    base_end = list_open(p, &base_content);
    p = base_content;

    while (p < base_end) {
        byte *content, *item_end;
        item_end = list_open(p, &content);
        if (content[0] == g_player_room)
            print_obj_name(content, item_end);
        p = item_end;
    }
    return 1;
}

/* 0x07: PrintRoom -- print current room description */
static int op_print_room(byte **pp, byte *end)
{
    print_room_desc();
    return 1;
}

/* 0x08: is_first_noun -- test if script object is the first noun.
 * Script byte is sequential object index; g_noun1_num is also sequential
 * index (converted from vocab word via obj_seq_from_tag in decode_tokens). */
static int op_is_first_noun(byte **pp, byte *end)
{
    byte num = *(*pp)++;
    if (!g_noun1_num) return 0;
    return (g_noun1_num == num) ? 1 : 0;
}

/* 0x09: is_second_noun -- test if script object is the second noun. */
static int op_is_second_noun(byte **pp, byte *end)
{
    byte num = *(*pp)++;
    if (!g_noun2_num) return 0;
    return (g_noun2_num == num) ? 1 : 0;
}

/* 0x0A: TestPhraseForm -- test if phrase_form == [*pp] */
static int op_test_phrase(byte **pp, byte *end)
{
    byte form = *(*pp)++;
    return (g_phrase_form == form) ? 1 : 0;
}

/* forward declarations for control-flow opcodes */
static int op_dispatch(byte **pp, byte *end);
static int op_do_list(byte **pp, byte *end);
static int op_do_list_all(byte **pp, byte *end);

/* 0x0C: assembly is "ora #$01; rts" => Z=0 => FAILURE in VM convention */
static int op_ret_false(byte **pp, byte *end)
{
    return 0;
}

/* 0x0F: SetObjRoomToActive -- set var_obj's room to active_obj */
static int op_set_obj_room_active(byte **pp, byte *end)
{
    if (g_var_obj_data) g_var_obj_data[0] = g_active_obj;
    return 1;
}

/* 0x10: DropObject -- set var_obj's room to cur_room */
static int op_drop_obj(byte **pp, byte *end)
{
    if (g_var_obj_data) g_var_obj_data[0] = g_cur_room;
    return 1;
}

/* 0x11: PrintNoun1Name */
static int op_print_noun1(byte **pp, byte *end)
{
    if (!g_noun1_data && g_noun1_num)
        g_noun1_data = obj_find_by_num(g_noun1_num, &g_noun1_end);
    if (g_noun1_data) print_obj_name(g_noun1_data, g_noun1_end);
    return 1;
}

/* 0x12: PrintNoun2Name */
static int op_print_noun2(byte **pp, byte *end)
{
    if (!g_noun2_data && g_noun2_num)
        g_noun2_data = obj_find_by_num(g_noun2_num, &g_noun2_end);
    if (g_noun2_data) print_obj_name(g_noun2_data, g_noun2_end);
    return 1;
}

/* 0x13: RunObjScripts -- run room/noun scripts; return 1 if any succeeded */
static int op_run_obj_scripts(byte **pp, byte *end)
{
    /* 1. Try room script (tag 0x04); skip 1 flags byte in room content */
    if (g_cur_room_data) {
        byte *rd = g_cur_room_data + 1;  /* +1 skips flags byte */
        byte *sc = list_find_tag(rd, g_cur_room_end, 0x04, NULL);
        if (sc) {
            byte *c, *se = list_end_from_len(sc, &c);
            if (exec_script(c, se)) return 1;
        }
    }

    /* 2. Try noun2 object script (tag 0x06 = "COMMAND HANDLING IF SECOND NOUN")
     * Assembly $0E8A: second noun is checked before first noun. */
    if (g_noun2_num) {
        byte *nd_end;
        byte *nd = obj_find_by_num(g_noun2_num, &nd_end);
        if (nd) {
            byte *sc = list_find_tag(nd + 3, nd_end, 0x06, NULL);
            if (sc) {
                byte *c, *se = list_end_from_len(sc, &c);
                if (exec_script(c, se)) return 1;
            }
        }
    }

    /* 3. Try noun1 object script (tag 0x07 = "COMMAND HANDLING IF FIRST NOUN") */
    if (g_noun1_num) {
        byte *nd_end;
        byte *nd = obj_find_by_num(g_noun1_num, &nd_end);
        if (nd) {
            byte *sc = list_find_tag(nd + 3, nd_end, 0x07, NULL);
            if (sc) {
                byte *c, *se = list_end_from_len(sc, &c);
                if (exec_script(c, se)) return 1;
            }
        }
    }

    return 0;  /* no applicable scripts found or all failed */
}

/* 0x14: execute_and_reverse_status -- execute next single command, invert result.
 * Assembly 0F28: JSR ProcessCommand (no length prefix, reads one command from X). */
static int op_do_list_not(byte **pp, byte *end)
{
    int r = exec_one(pp, end);
    return r ? 0 : 1;
}

/* 0x15: TestObjBit -- test bit in var_obj's bits byte */
static int op_test_obj_bit(byte **pp, byte *end)
{
    byte bitmask = *(*pp)++;
    if (!g_var_obj_data) return 1;
    return (g_var_obj_data[2] & bitmask) == bitmask ? 1 : 0;
}

/* 0x16: PrintVarObjName */
static int op_print_varobj(byte **pp, byte *end)
{
    if (g_var_obj_data) print_obj_name(g_var_obj_data, g_var_obj_end);
    return 1;
}

/* 0x17: move_to -- set object [*pp]'s room to room [*pp+1] */
static int op_move_to(byte **pp, byte *end)
{
    byte obj_num  = *(*pp)++;
    byte room_num = *(*pp)++;
    byte *content = obj_find_by_num(obj_num, NULL);
    if (content) content[0] = room_num;
    return 1;
}

/* 0x18: is_VAR_owned_by_ACTIVE -- check if var_obj is carried by active obj */
static int op_is_varobj_owned_by_active(byte **pp, byte *end)
{
    return obj_owned_by_active(g_var_obj_data);
}

/* 0x19: GoRoom -- go to room [*pp] without printing */
static int op_go_room(byte **pp, byte *end)
{
    byte room = *(*pp)++;
    go_room(room);
    {
        byte *ac = obj_find_by_num(g_active_obj, NULL);
        if (ac) ac[0] = room;
    }
    return 1;
}

/* 0x1A: SetVarToNoun1 */
static int op_set_var_noun1(byte **pp, byte *end)
{
    g_var_obj_num = g_noun1_num;
    if (!g_noun1_data && g_noun1_num)
        g_noun1_data = obj_find_by_num(g_noun1_num, &g_noun1_end);
    g_var_obj_data = g_noun1_data;
    g_var_obj_end  = g_noun1_end;
    return 1;
}

/* 0x1B: SetVarToNoun2 */
static int op_set_var_noun2(byte **pp, byte *end)
{
    g_var_obj_num = g_noun2_num;
    if (!g_noun2_data && g_noun2_num)
        g_noun2_data = obj_find_by_num(g_noun2_num, &g_noun2_end);
    g_var_obj_data = g_noun2_data;
    g_var_obj_end  = g_noun2_end;
    return 1;
}

/* 0x1C: SetVarObj -- var_obj = object number [*pp] */
static int op_set_var_obj(byte **pp, byte *end)
{
    byte num = *(*pp)++;
    g_var_obj_num  = num;
    g_var_obj_data = (num == 0) ? NULL : obj_find_by_num(num, &g_var_obj_end);
    if (num == 0) g_var_obj_end = NULL;
    return 1;
}

/* 0x1D: Damage -- subtract [*pp] hitpoints from var_obj */
static int op_damage(byte **pp, byte *end)
{
    byte dmg = *(*pp)++;
    byte *hpptr;
    if (!g_var_obj_data || !g_var_obj_num) return 0;
    {
        byte *obj_end;
        obj_find_by_num(g_var_obj_num, &obj_end);
        hpptr = list_find_tag(g_var_obj_data + 3, obj_end, 0x09, NULL);
        if (hpptr) {
            byte *c; list_end_from_len(hpptr, &c);
            if (c[1] >= dmg) c[1] -= dmg; else c[1] = 0;
            if (c[1] == 0) {
                byte *ds = list_find_tag(g_var_obj_data + 3, obj_end, 0x0A, NULL);
                if (ds) {
                    byte *dc, *de = list_end_from_len(ds, &dc);
                    exec_script(dc, de);
                }
            }
            return 1;
        }
    }
    return 0;
}

/* 0x1E: SwapObjRooms */
static int op_swap_obj_rooms(byte **pp, byte *end)
{
    byte num1 = *(*pp)++;
    byte num2 = *(*pp)++;
    byte *o1 = obj_find_by_num(num1, NULL);
    byte *o2 = obj_find_by_num(num2, NULL);
    if (o1 && o2) {
        byte tmp = o1[0]; o1[0] = o2[0]; o2[0] = tmp;
    }
    return 1;
}

/* 0x1F: print2 -- print packed msg only if player is in current room */
static int op_print2(byte **pp, byte *end)
{
    byte *msg = *pp;
    byte *content;
    byte *msg_end = list_end_from_len(msg, &content);
    *pp = msg_end;
    if (obj_in_cur_room_or_pack(g_player_room))
        print_packed(msg);
    return 1;
}

/* 0x20: ChkActiveRoom -- compare active_obj with [*pp] */
static int op_chk_active_room(byte **pp, byte *end)
{
    byte val = *(*pp)++;
    return (g_active_obj == val) ? 1 : 0;
}

/* 0x21: SubScript -- run cmd_data with modified noun/phrase context */
static int op_sub_script(byte **pp, byte *end)
{
    byte phrase = *(*pp)++;
    byte n1     = *(*pp)++;
    byte n2     = *(*pp)++;
    byte save_phrase = g_phrase_form;
    byte save_n1 = g_noun1_num, save_n2 = g_noun2_num;
    byte *save_n1d = g_noun1_data, *save_n2d = g_noun2_data;
    byte *save_n1e = g_noun1_end,  *save_n2e = g_noun2_end;
    int r;

    g_phrase_form = phrase;
    g_noun1_num   = n1;
    g_noun2_num   = n2;
    g_noun1_data  = n1 ? obj_find_by_num(n1, &g_noun1_end) : NULL;
    g_noun2_data  = n2 ? obj_find_by_num(n2, &g_noun2_end) : NULL;
    if (!n1) g_noun1_end = NULL;
    if (!n2) g_noun2_end = NULL;

    {
        byte *cc, *ce;
        ce = list_open(cmd_data, &cc);
        r  = exec_script(cc, ce);
    }

    g_phrase_form = save_phrase;
    g_noun1_num   = save_n1;  g_noun2_num   = save_n2;
    g_noun1_data  = save_n1d; g_noun2_data  = save_n2d;
    g_noun1_end   = save_n1e; g_noun2_end   = save_n2e;
    return r;
}

/* 0x22: HPGreaterThan -- var_obj's HP > [*pp] */
static int op_hp_gt(byte **pp, byte *end)
{
    byte threshold = *(*pp)++;
    byte *oe, *hpptr;
    if (!g_var_obj_data) return 1;
    obj_find_by_num(g_var_obj_num, &oe);
    hpptr = list_find_tag(g_var_obj_data + 3, oe, 0x09, NULL);
    if (!hpptr) return 1;
    {
        byte *c; list_end_from_len(hpptr, &c);
        return (c[1] > threshold) ? 0 : 1;
    }
}

/* 0x23: AddHP */
static int op_add_hp(byte **pp, byte *end)
{
    byte add = *(*pp)++;
    byte *oe, *hpptr;
    if (!g_var_obj_data) return 0;
    obj_find_by_num(g_var_obj_num, &oe);
    hpptr = list_find_tag(g_var_obj_data + 3, oe, 0x09, NULL);
    if (hpptr) {
        byte *c; list_end_from_len(hpptr, &c);
        if ((word)c[1] + add > 0xFF) c[1] = 0xFF;
        else c[1] = (byte)(c[1] + add);
    }
    return 1;
}

/* 0x24: Halt -- game over */
static int op_halt(byte **pp, byte *end)
{
    print_char('\r');
    flush_line();
    printf("GAME OVER\n");
    exit(0);
    return 0;
}

/* 0x25: Restart */
static int op_restart(byte **pp, byte *end)
{
    print_char('\r'); print_char('\r');
    flush_line();
    return 2;
}

/* 0x26: PrintScore -- print score as two decimal digits + ". "
 * Assembly $10C5: objects in treasure room (0x96) count double; carried objects
 * also count double if player is currently in the treasure room. */
static int op_print_score(byte **pp, byte *end)
{
    byte *p = obj_data;
    byte *base_end, *base_content;
    int score = 0;
    int in_treasure = (g_cur_room == 0x96);

    base_end = list_open(p, &base_content);
    p = base_content;

    while (p < base_end) {
        byte *content, *item_end;
        item_end = list_open(p, &content);
        if (content[1] != 0) {
            byte loc = content[0];
            if (loc == 0x96) {
                score += content[1];
                score += content[1];   /* treasure room always counts double */
            } else if (loc == g_player_room) {
                score += content[1];
                if (in_treasure) score += content[1]; /* double if player in treasure */
            }
        }
        p = item_end;
    }

    print_char('0' + score / 10);
    print_char('0' + score % 10);
    print_char('.');
    print_char(' ');
    return 1;
}

/* ---- exec_script: core VM loop ------------------------------------------ */

typedef int (*opfunc)(byte **pp, byte *end);

static opfunc optable[39] = {
    op_go_room_print,       /* 0x00 */
    op_check_obj,           /* 0x01 */
    op_is_owned_by_active,  /* 0x02 */
    op_cmp_obj_room,        /* 0x03 */
    op_print_msg,           /* 0x04 */
    op_cmp_rand,            /* 0x05 */
    op_print_invent,        /* 0x06 */
    op_print_room,          /* 0x07 */
    op_is_first_noun,       /* 0x08 */
    op_is_second_noun,      /* 0x09 */
    op_test_phrase,         /* 0x0A */
    op_dispatch,            /* 0x0B */
    op_ret_false,           /* 0x0C */
    op_do_list,             /* 0x0D */
    op_do_list_all,         /* 0x0E */
    op_set_obj_room_active, /* 0x0F */
    op_drop_obj,            /* 0x10 */
    op_print_noun1,         /* 0x11 */
    op_print_noun2,         /* 0x12 */
    op_run_obj_scripts,     /* 0x13 */
    op_do_list_not,         /* 0x14 */
    op_test_obj_bit,        /* 0x15 */
    op_print_varobj,        /* 0x16 */
    op_move_to,             /* 0x17 */
    op_is_varobj_owned_by_active, /* 0x18 */
    op_go_room,             /* 0x19 */
    op_set_var_noun1,       /* 0x1A */
    op_set_var_noun2,       /* 0x1B */
    op_set_var_obj,         /* 0x1C */
    op_damage,              /* 0x1D */
    op_swap_obj_rooms,      /* 0x1E */
    op_print2,              /* 0x1F */
    op_chk_active_room,     /* 0x20 */
    op_sub_script,          /* 0x21 */
    op_hp_gt,               /* 0x22 */
    op_add_hp,              /* 0x23 */
    op_halt,                /* 0x24 */
    op_restart,             /* 0x25 */
    op_print_score,         /* 0x26 */
};

/* Execute one opcode from *pp (advancing *pp past it).
 * Returns 0=continue, 1=stop, 2=restart. */
static int exec_one(byte **pp, byte *end)
{
    byte op = *(*pp)++;

    if (op & 0x80) {
        /* Common command: find in ccmd_data by tag */
        byte *p = ccmd_data;
        byte *base_end, *base_content;
        base_end = list_open(p, &base_content);
        p = base_content;
        while (p < base_end) {
            byte tag = *p;
            byte *content, *item_end;
            item_end = list_open(p, &content);
            if (tag == op)
                return exec_script(content, item_end);
            p = item_end;
        }
        return 0;
    }

    if (op < 39) {
        return optable[op](pp, end);
    }

    /* Opcodes 0x27-0x7F: single-byte TestAndExecute.
     * Format: [phrase_form] [block_size] [block_size bytes of script]
     * Execute block if g_phrase_form matches, else skip it. */
    {
        byte block_size = *(*pp)++;
        byte *block_start = *pp;
        byte *block_end   = block_start + block_size;
        *pp = block_end;
        if (g_phrase_form == op)
            return exec_script(block_start, block_end);
        return 0;
    }
}

static int exec_script(byte *p, byte *end)
{
    while (p < end) {
        int r = exec_one(&p, end);
        if (r) return r;
    }
    return 0;
}

/* 0x0B: dispatch -- switch/case: first content byte is test opcode; then
 * [test_arg...][action_list] pairs; on first matching test, run action and return */
static int op_dispatch(byte **pp, byte *end)
{
    byte *p = *pp;
    byte *content;
    byte *sub_end = list_end_from_len(p, &content);
    *pp = sub_end;

    if (content >= sub_end) return 0;

    {
        byte test_op = *content++;
        byte *item = content;

        while (item < sub_end) {
            /* Run test opcode against its argument(s) */
            byte *test_pp = item;
            int test_result = (test_op < 39) ? optable[test_op](&test_pp, sub_end) : 0;
            item = test_pp;

            {
                /* Parse action list (skip it regardless) */
                byte *action_content;
                byte *action_end = list_end_from_len(item, &action_content);
                if (test_result) {
                    byte *aip = action_content;
                    return exec_one(&aip, action_end);
                }
                item = action_end;
            }
        }
    }
    return 0;
}

/* 0x0D: DoList -- AND: stop on first failure; return 1 if ALL items succeed */
static int op_do_list(byte **pp, byte *end)
{
    byte *p = *pp;
    byte *content;
    byte *sub_end = list_end_from_len(p, &content);
    byte *item = content;

    *pp = sub_end;

    while (item < sub_end) {
        int r = exec_one(&item, sub_end);
        if (!r) return 0;  /* first failure stops the list */
    }
    return 1;  /* all items succeeded */
}

/* 0x0E: DoListAll -- short-circuit OR: stop on first success */
static int op_do_list_all(byte **pp, byte *end)
{
    byte *p = *pp;
    byte *content;
    byte *sub_end = list_end_from_len(p, &content);
    byte *item = content;

    *pp = sub_end;

    while (item < sub_end) {
        int r = exec_one(&item, sub_end);
        if (r) return 1;  /* stop on first success */
    }
    return 0;
}

/* ---- turn scripts: run tag=08 script for every object ------------------- */
/* Assembly X9: skips objects with room=0 (beq L0FC9).
 * Sets $01D5 to the object's room before running its script (L0FB8: stb >$01D5).
 * player_room is saved/restored around this in game_turn. */
static void run_turn_scripts(byte player_room)
{
    byte *p = obj_data;
    byte *base_end, *base_content;
    byte obj_idx = 0;   /* 1-based sequential index, matches assembly tmp1DO */

    base_end = list_open(p, &base_content);
    p = base_content;

    while (p < base_end) {
        byte *content, *item_end;
        byte *tsc;
        byte obj_room;
        item_end = list_open(p, &content);
        obj_idx++;
        obj_room = content[0];
        tsc = list_find_tag(content + 3, item_end, 0x08, NULL);
        if (tsc && obj_room != 0) {
            byte *tc, *te = list_end_from_len(tsc, &tc);
            rand_next();   /* assembly $0F95: roll once per object with a turn script */
            /* follow owner chain to find room (assembly $0FA7-$0FB6) */
            while (!(obj_room & 0x80)) {
                byte *owner;
                if (obj_room == g_player_room) { obj_room = player_room; break; }
                owner = obj_find_by_num(obj_room, NULL);
                if (!owner) { obj_room = 0; break; }
                obj_room = owner[0];
                if (!obj_room) break;
            }
            if (!obj_room) { p = item_end; continue; }
            go_room(obj_room);
            g_active_obj      = obj_idx;    /* sequential index, not tag byte */
            g_active_obj_data = content;
            g_active_obj_end  = item_end;
            exec_script(tc, te);
        }
        p = item_end;
    }
    g_active_obj      = g_player_room;
    g_active_obj_data = NULL;
    g_active_obj_end  = NULL;
}

/* ---- input reading ------------------------------------------------------ */
/* Assembly rolls once per keystroke (GetKey, $0B2B) for every character read,
 * including the terminating CR and characters typed past the buffer limit. */
static void read_input(void)
{
    int c, i = 0;
    flush_line();
    printf("> ");
    fflush(stdout);

    while (i < INPUT_LEN - 1) {
        c = getchar();
        if (c == EOF) { g_input[0] = '\1'; return; }  /* signal EOF */
        rand_next();
        if (c == '\n' || c == '\r') break;
        if (c >= 'a' && c <= 'z') c -= 32;
        if ((c >= 'A' && c <= 'Z') || c == ' ')
            g_input[i++] = (char)c;
    }
    g_input[i] = '\0';
    while (c != EOF && c != '\n' && c != '\r') {
        c = getchar();
        if (c != EOF) rand_next();
    }
}

/* ---- main game loop ----------------------------------------------------- */
static void game_init(void)
{
    rand_init();

    g_player_room     = 0x1D;   /* sentinel: active_obj when player is acting */
    g_active_obj      = g_player_room;
    g_active_obj_data = NULL;
    g_active_obj_end  = NULL;

    go_room(0x96);              /* assembly: ldb #$96; stb >$01D5 */

    g_line_len = 0;
    g_col = 0;
}

static void game_turn(void)
{
    byte *cc, *ce;

    g_verb = 0; g_prep = 0; g_prep_given = 0;
    g_adj  = 0; g_cmd_targ = 0;
    g_noun1_num = 0; g_noun2_num = 0;
    g_noun1_typed = 0; g_noun2_typed = 0;
    g_noun1_data = NULL; g_noun1_end = NULL;
    g_noun2_data = NULL; g_noun2_end = NULL;
    g_var_obj_num = 0;
    g_var_obj_data = NULL; g_var_obj_end = NULL;
    g_token_count = 0;
    g_phrase_form = 0;

    parse_input();
    decode_tokens();

    if (g_verb == 0 && g_token_count == 0) {
        print_plain(msg_qverb);
        return;
    }

    /* Assembly $0822: noun typed but no accessible object found → ?WHAT? */
    if ((g_noun1_typed && !g_noun1_num) || (g_noun2_typed && !g_noun2_num)) {
        print_plain(msg_qwhat);
        return;
    }

    {
        int pform = find_phrase_form();
        if (pform == -2) {
            /* user gave a noun the matched phrase doesn't take → ?PHRASE? (assembly $07B7/$07DD) */
            print_plain(msg_qphrase);
            return;
        }
        if (pform < 0) {
            /* scan found no/multiple matching objects → ?WHAT? (assembly $095A→$0983) */
            print_plain(msg_qwhat);
            return;
        }
        g_phrase_form = (byte)pform;
    }
    if (g_phrase_form == 0 && g_verb == 0) {
        print_plain(msg_qverb);
        return;
    }

    if (g_noun1_num)
        g_noun1_data = obj_find_by_num(g_noun1_num, &g_noun1_end);
    if (g_noun2_num)
        g_noun2_data = obj_find_by_num(g_noun2_num, &g_noun2_end);

    /* Assembly $07FD: if no first noun was given, promote second noun to first.
     * This ensures tag-0x07 (first-noun handler) fires for "LOOK UNDER RUG"
     * where the noun is parsed into the second slot due to the preposition. */
    if (!g_noun1_num && g_noun2_num) {
        g_noun1_num  = g_noun2_num;
        g_noun1_data = g_noun2_data;
        g_noun1_end  = g_noun2_end;
    }

    ce = list_open(cmd_data, &cc);
    exec_script(cc, ce);

    {
        byte player_room = g_cur_room;
        byte *pd;
        run_turn_scripts(player_room);
        /* After scripts, player may have been teleported (e.g. after death/restart).
         * Read the player object's actual room instead of the pre-turn snapshot. */
        pd = obj_find_by_num(g_player_room, NULL);
        go_room((pd && pd[0]) ? pd[0] : player_room);
    }

    print_char('\r');
    flush_line();
}

int main(void)
{
    game_init();

    printf("RAAKA-TU\n\n");

    print_room_desc();
    flush_line();

    while (1) {
        read_input();
        if (g_input[0] == '\1') break;  /* EOF */
        if (g_input[0] == '\0') continue;
        game_turn();
    }

    return 0;
}
